#!/bin/sh

echo "***********************************"
echo "*            Pluto-TV             *"
echo "*               by                *"
echo "*          xcentaurix             *"
echo "***********************************"
echo ""
echo "Plugin Pluto-TV installed successfully."
echo "Please restart Enigma2 now!"
echo ""
exit 0
