#!/bin/sh
if [ "$1" = "remove" ]; then
	echo "Removing Pluto-TV plugin from the system ..."
	rm -rf /usr/lib/enigma2/python/Plugins/Extensions/Pluto-TV > /dev/null 2>&1
else
	find /usr/lib/enigma2/python/Plugins/Extensions/Pluto-TV -type f -name "*.pyc" -exec rm -f {} \; > /dev/null 2>&1
fi
exit 0
